### ISSUE TITLE
Roadmap for version 1.0

### ISSUE THREAD

**Issue by HDembinski** [impy-project/chromo#165]
Before we release a version 1.0, we need to fix/settle a couple of things that will be breaking changes for some users.

- [x] Unify the event records for all generators. SIBYLL does not include the beam particles. The event record should always include the beam particles. #101
- [x] In the parent and children vector, the indices start with 1. They should start with 0 so that these indices can be directly to fetch other numbers from the EventData arrays px, pid, ... #100
- [x] The QGSJet family does not decay pi0. When Chromo is run with default settings, the final state should be defined identically for all models. For QGSJet, we need to decay the pi0 to make it consistent. #87

Ping @afedynitch @jncots

**Comment by jncots** [comment]
Ok. I will try to fix #100 for a start.

**Comment by HDembinski** [comment]
@jncots Thanks! It is technically easy, but it is a delicate change to the API. We should not just change the indices returned in the children and parent arrays in EventData, because that would silently break everyones code that is doing the subtraction of 1 manually at the moment. I do that in all my scripts, for example.

I propose the following.
- Visually deprecate the current accessors with warnings. numpy has a `VisibleDeprecationWarning` that we can use.
- Add two new accessors which return the index - 1. These need new names. Unfortunately, we used the best names already for the current accessors. We should not just call them parents2 and children2. It is not as political correct, but I propose to use mothers and daughters.
- For a few versions we provide all of them, parents, children, mothers, daugthers.
- Then we eventually remove parents and children.

This how one gracefully changes the API without too much pain for the users.

Since we do not have so many users yet, we could shorten this and just remove parents and children without deprecation. But it is important that code which uses the old accessors with the old indexing convention (parents, children) fails in obvious ways instead of doing something wrong without giving any errors.
